# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-30 18:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quit', '0003_auto_20170530_1319'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Something',
            new_name='Thing',
        ),
    ]
